fail fast if no diffs detected between current commit and new commit

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -26,10 +26,18 @@ jobs:
 
       - name: Commit and push
         run: |
+          # set author to actions
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git add snapcraft.yaml
-          git diff --quiet && git diff --staged --quiet || (git commit -m "Bump version to ${{ steps.get_tag.outputs.tag }}" && git push)
+          git add snapcraft.yaml # add the one file we change
+          # check for any commits
+          if git diff --quiet && git diff --staged --quiet; then
+            echo "Ehh, nothin's new. Peace out."
+            exit 1 # fails fast
+          fi
+          # else do the commit
+          git commit -m "Bump version to ${{ steps.get_tag.outputs.tag }}"
+          git push
   build-after-publish:
     name: Build snap
     needs: [update-snap]
